- project:
    name: openstack/puppet-pacemaker
    check:
      jobs:
        - puppet-openstack-lint:
            override-checkout: stable/ocata
        - puppet-openstack-syntax-4:
            override-checkout: stable/ocata
        - puppet-openstack-unit-4.8-centos-7:
            override-checkout: stable/ocata
    gate:
      jobs:
        - puppet-openstack-lint:
            override-checkout: stable/ocata
        - puppet-openstack-syntax-4:
            override-checkout: stable/ocata
        - puppet-openstack-unit-4.8-centos-7:
            override-checkout: stable/ocata
