- project:
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
      - release-notes-jobs-python3
    check:
      jobs:
        - tripleo-ci-centos-8-scenario004-standalone:
            vars:
              build_container_images: true
    gate:
      jobs:
        - tripleo-ci-centos-8-scenario004-standalone:
            vars:
              build_container_images: true
      queue: tripleo

