- project:
    name: openstack/puppet-pacemaker
    templates:
      - puppet-openstack-check-jobs
      - puppet-openstack-module-unit-jobs
    check-tripleo:
      jobs:
        - tripleo-ci-centos-7-ovb-ha-oooq
